import numpy as np
import spikeinterface.full as si
from spikeinterface.extractors import read_kilosort, BinaryRecordingExtractor
from pathlib import Path

folder = Path("../kilosort4_output/sorter_output")
analyzer_folder = Path("../zahra_run/analyzer/group0")

sampling_frequency = 30000.0

# ------------------------------------------------------------------
# Load the original Kilosort outputs
# ------------------------------------------------------------------

sorting = read_kilosort(folder, keep_good_only=False)

templates = np.load(folder / "templates.npy")
channel_positions = np.load(folder / "channel_positions.npy")

print("Kilosort templates:", templates.shape)
print("Kilosort channel positions:", channel_positions.shape)

# templates.npy = (n_units, n_samples, n_channels)
n_template_channels = templates.shape[2]

if channel_positions.shape[0] != n_template_channels:
    raise ValueError(
        f"Mismatch between Kilosort templates and channel positions: "
        f"{n_template_channels} template channels vs "
        f"{channel_positions.shape[0]} channel positions."
    )

# ------------------------------------------------------------------
# Determine the channel mapping used by Kilosort
# ------------------------------------------------------------------

channel_map_file = folder / "channel_map.npy"

if channel_map_file.exists():
    channel_map = np.load(channel_map_file).astype(int).ravel()

    if len(channel_map) != n_template_channels:
        raise ValueError(
            f"channel_map.npy contains {len(channel_map)} channels, "
            f"but templates.npy contains {n_template_channels} channels."
        )
else:
    channel_map = np.arange(n_template_channels, dtype=int)

# Kilosort's channel_map is commonly zero-based in the saved numpy file,
# but verify that it is a valid mapping.
if np.any(channel_map < 0):
    raise ValueError("channel_map.npy contains negative channel indices.")

# ------------------------------------------------------------------
# Construct the recording using the exact channel ordering represented
# by Kilosort's templates.
# ------------------------------------------------------------------

recording = BinaryRecordingExtractor(
    file_paths=[folder / "recording.dat"],
    sampling_frequency=sampling_frequency,
    num_channels=n_template_channels,
    dtype="int16",
    time_axis=0,
)

recording_channel_ids = np.asarray(recording.get_channel_ids())

if len(recording_channel_ids) != len(channel_map):
    raise ValueError(
        f"recording.dat has {len(recording_channel_ids)} channels, "
        f"but Kilosort expects {len(channel_map)} template channels."
    )

# Kilosort channel positions correspond to the template channel order.
recording.set_channel_locations(channel_positions)

# ------------------------------------------------------------------
# Preserve Kilosort properties
# ------------------------------------------------------------------

for key in ["KSLabel", "KSLabel_repeat"]:
    vals = sorting.get_property(key)
    if vals is not None:
        sorting.set_property(key, np.asarray(vals).astype(str))

# ------------------------------------------------------------------
# Create the SortingAnalyzer
# ------------------------------------------------------------------

analyzer = si.create_sorting_analyzer(
    sorting=sorting,
    recording=recording,
    format="zarr",
    folder=analyzer_folder,
    overwrite = True
)

# ------------------------------------------------------------------
# IMPORTANT:
# Do NOT compute "waveforms" or "templates" from recording.dat here.
#
# The original Kilosort templates are preserved separately and should
# be supplied to the Phy exporter directly rather than regenerated by
# SpikeInterface.
# ------------------------------------------------------------------

unit_ids = np.asarray(sorting.get_unit_ids())

if templates.shape[0] != len(unit_ids):
    raise ValueError(
        f"Kilosort contains {templates.shape[0]} templates, "
        f"but the SpikeInterface sorting contains {len(unit_ids)} units."
    )

# Verify the template/channel relationship before exporting.
template_peak_channels = np.argmin(
    np.min(templates, axis=1),
    axis=1,
)

if np.any(template_peak_channels >= n_template_channels):
    raise ValueError("Invalid peak channel detected in Kilosort templates.")

print()
print("Kilosort data loaded without recomputing templates.")
print(f"Units: {len(unit_ids)}")
print(f"Template shape: {templates.shape}")
print(f"Template channels: {n_template_channels}")
print(f"Channel map: {channel_map}")
print()

# ------------------------------------------------------------------
# Save the original Kilosort templates and channel map alongside the
# analyzer so export_to_phy can use them without changing its code.
# ------------------------------------------------------------------

np.save(analyzer_folder / "kilosort_templates.npy", templates)
np.save(analyzer_folder / "kilosort_channel_map.npy", channel_map)
np.save(
    analyzer_folder / "kilosort_channel_positions.npy",
    channel_positions,
)

print("Saved original Kilosort templates and channel mapping.")